### ISSUE TITLE
Incompatible ClockTypes between Node() and Time() objects

### ISSUE THREAD

**Issue by zmontross** [zmontross/SPD-13#2]
Node() objects default to ClockType.ROS_TIME (found in _clock.py:ROSClock(Clock)_).
Time() objects default to ClockType.SYSTEM_TIME (found in _time.py:Time()_).

It doesn't look like nodes have an obvious way of changing their clock post-instantiation / during _init()_.

Need to resolve this so that we can do basic delta-time calculations (needed to compute velocity, etc.).

```
speedy@spd-13:~/spd_13$ source ./install/setup.bash
speedy@spd-13:~/spd_13$ 
speedy@spd-13:~/spd_13$ ros2 run spd_13 differential_odometry
Traceback (most recent call last):
  File "/home/speedy/spd_13/install/spd_13/lib/spd_13/differential_odometry", line 11, in <module>
    load_entry_point('spd-13==0.0.0', 'console_scripts', 'differential_odometry')()
  File "/home/speedy/spd_13/install/spd_13/lib/python3.8/site-packages/spd_13/differential_odometry.py", line 206, in main
    diff_odom = DifferentialOdometry()
  File "/home/speedy/spd_13/install/spd_13/lib/python3.8/site-packages/spd_13/differential_odometry.py", line 76, in __init__
    self.update_tlast = Time(nanoseconds=self.get_clock().now().nanoseconds, clock_type=self.get_clock())
  File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/time.py", line 28, in __init__
    raise TypeError('Clock type must be a ClockType enum')
TypeError: Clock type must be a ClockType enum
speedy@spd-13:~/spd_13$ 
```

**Comment by zmontross** [comment]
`self.get_clock().now()` is enough to fix this. When getting the current time this will fetch time from the Node's clock, and `now()` returns a `Time()` object with the appropriate properties.
